version: '3.7'
services:

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5431:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_LOGIN}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/psql/data

  redis:
    image: redis:alpine
    command: redis-server

  app:
    build:
      dockerfile: app.Dockerfile
    container_name: app
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
  
  celery:
    build:
      dockerfile: celery.Dockerfile
    container_name: celery
    env_file:
      - .env
    depends_on:
      - app

volumes:
  postgres_data: