AUTH_ROUTE_URI = "/auth"
API_ROUTER = "/v1/api"
USER_ROUTE_URI = API_ROUTER + "/users"
PRODUCT_ROUTER_API = API_ROUTER + "/products"

MIN_USERNAME_LENGHT = 3
MAX_USERNAME_LENGHT = 25

MIN_PASSWORD_LENGHT = 9
MAX_PASSWORD_LENGHT = 90

MIN_PRODUCT_TITLE_LENGHT = 3

CACHE_TTL_SEC = 600
